# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=256)),
                ('spanish', models.CharField(max_length=256)),
            ],
        ),
    ]
